### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by 2uan2** [3-I-Projects/QAirline#2]
# Overview
A place to track things to be done according to the QAirline requirement
# Tasks
- [x] backend
- [x] Admin dashboard
  - [x] Admin login authentication using access token
    - [x] Auto redirect to /admin/dashboard from /admin if admin already logged in 
  - [ ] Admin login authentication using refresh token
  - [x] Styling for admin dashboard
  - [x] Posts management
  - [x] Flights management
  - [x] Customers management
  - [x] Planes management
  - [x] Airports management
  - [x] Set flight delay
  - [ ] Seats management
- [x] frontend
  - [x] User's profile page
  - [x] User's booking page
  - [x] Seat picker page
  - [x] add logic for round trip flight
  - [x] section that shows what currently selected ticket looks like
  - [x] complete ticket booking process
    - [x] find flight from home and gets directed to page with flight list
    - [x] choose flight from flight list and gets taken to user info form page
    - [x] fill info and gets taken to seat picker page
      - [x] (optional) choose from customers you've booked tickets for before if logged in
    - [x] choose seat and gets taken to payment form
      - [x] (optional) user doesn't choose seats and get randomly assigned to an economy seat
    - [x] pay and gets directed to home (or should it be user's booking page??)
- [x] styling, a lot of it
  - [x] add footer maybe
  - [ ] ~~graph of flights sorted by day with prices~~
  - [x] bug where can't scroll up in /detail
  - [x] add Pay now button to QR Payment
  - [x] my booking page
  - [x] announcement, and make home page less empty
  - [x] add menu to most pages
  - [x] entire admin dashboard:v
  - [x] fix text of all pages
  - [x] seat picker
  - [x] maybe dark theme
  - [ ] ~~maybe animation~~
  - [x] fix some hover margin in menu

Written following guide here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

**Comment by GoatYogurt** [comment]
vậy là cũng đến lúc phải nói chia tay, nhanh quá huhu

**Comment by 2uan2** [comment]
hoàn thiện nốt admin đi:)))))

**Comment by GoatYogurt** [comment]
haizzz thiếu cái seats management
